language: node_js
node_js:
    - "0.10"
before_script:
    - "cd ../"
    - "git clone git@github.com:uupaa/WebModule.git"
    - "cd -"
    - "npm install"
    - "npm install uupaa.compile.js"
    - "npm run minify"
script:
    - "npm run node"


