language: node_js
node_js:
    - "0.10"
before_script:
    - "pwd"
    - "npm install"
    - "npm install uupaa.closurecompiler.js"
    - "node node_modules/uupaa.closurecompiler.js --output ./release/UID.min.js --source lib/Minify.js"
script:
    - "npm run node"


